# ProGuard / R8 Rules for FlexKeypad

# 1. Kotlinx Serialization
# Keep all @Serializable annotated classes and their serializers
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.SerializationKt

-keepclassmembers class * {
    @kotlinx.serialization.SerialName <fields>;
}

-keepclassmembers class * {
    *** Companion;
}

-keepclasseswithmembers class * {
    kotlinx.serialization.KSerializer $serializer;
}

-keep,allowobfuscation,allowshrinking class * {
    <fields>;
}

# Explicitly keep FlexKeypad domain models serialized to JSON
-keep class com.emoulya.flexkeypad.domain.model.KeypadProfile { *; }
-keep class com.emoulya.flexkeypad.domain.model.KeypadButton { *; }
-keep class com.emoulya.flexkeypad.domain.model.ModifierKey { *; }
-keep class com.emoulya.flexkeypad.data.usb.UsbKeyEvent { *; }

# Keep Serializer classes generated by Kotlinx Serialization
-keep class com.emoulya.flexkeypad.domain.model.**$$serializer { *; }
-keepclassmembers class com.emoulya.flexkeypad.domain.model.** {
    *** Companion;
    *** serializer(...);
}
-keep class com.emoulya.flexkeypad.data.usb.**$$serializer { *; }
-keepclassmembers class com.emoulya.flexkeypad.data.usb.** {
    *** Companion;
    *** serializer(...);
}

# 2. AndroidX DataStore Preferences
-keepclassmembers class androidx.datastore.preferences.protobuf.GeneratedMessageLite {
    <fields>;
}

# 3. Android Bluetooth HID Device
-keepclassmembers class * extends android.bluetooth.BluetoothHidDevice$Callback {
    *;
}

# 4. Coroutines
-dontwarn kotlinx.coroutines.**
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
